trigger:
  branches:
    include:
      - main
      - seal-main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    displayName: "Install Node.js"
    inputs:
      version: "22.22.1"

  - task: SonarQubePrepare@7
    displayName: SonarQubePrepare - branch analysis
    condition: and(succeeded(), eq(variables['System.PullRequest.PullRequestId'], ''))
    inputs:
      SonarQube: 'SonarQube' # service connection name
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'IIoT---EdgeConfig-Frontend'
      cliProjectName: 'IIoT---EdgeConfig-Frontend'
      extraProperties: |
        sonar.branch.name=$(Build.SourceBranchName)
        sonar.sources=src
        sonar.exclusions=**/__tests__/**,**/node_modules/**
        sonar.tests=src
        sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.cy.tsx
        sonar.javascript.lcov.reportPaths=coverage/lcov.info

  - task: SonarQubePrepare@7
    condition: and(succeeded(), ne(variables['System.PullRequest.PullRequestId'], ''))
    displayName: SonarQubePrepare - Pull Request analysis
    inputs:
      SonarQube: 'SonarQube' # service connection name
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'IIoT---EdgeConfig-Frontend'
      cliProjectName: 'IIoT---EdgeConfig-Frontend'
      extraProperties: |
        sonar.pullrequest.key=$(System.PullRequest.PullRequestId)
        sonar.pullrequest.branch=$(System.PullRequest.SourceBranch)
        sonar.sources=src
        sonar.exclusions=**/__tests__/**,**/node_modules/**
        sonar.tests=src
        sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.cy.tsx
        sonar.javascript.lcov.reportPaths=coverage/lcov.info

  - script: |
      npm ci
    displayName: "Install node dependencies (ci)"

  - script: |
      npm run test:ci
    displayName: "Run vitest"

  - script: |
      npm run test:cypress:component:ci
    displayName: "Run cypress component tests"

  - script: |
      npm run combine:reports
    displayName: "Combine reports"

  - task: PublishTestResults@2
    displayName: "Publish test results"
    condition: succeededOrFailed() # because otherwise we won't know what tests failed
    inputs:
      testResultsFiles: "/home/vsts/work/1/s/reports/combined-report.xml"

  - task: PublishCodeCoverageResults@2
    displayName: "Publish code coverage"
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml"
      reportDirectory: "$(Build.SourcesDirectory)/coverage"
      failIfCoverageEmpty: true
  
  - task: SonarQubeAnalyze@7
    displayName: "Run SonarQube scan"

  - task: SonarQubePublish@7
    displayName: "Publish SonarQube results"
    inputs:
      pollingTimeoutSec: '300'